// GENERATED by `npm run fixtures` (scripts/find-fixtures.mjs). Do not hand-edit the answer sets:
// they are searched for against FIXTURE_EXPECTATIONS, so any change to the item set is answered by
// re-running the script rather than by re-tuning eighteen indices by hand.
//
// Each fixture is a full 24-answer session -- the 18 foundation answers plus an answer to each of
// the six adaptive questions those answers select.
import type { AnswerRecord } from "./scoring";
import { scoreAssessment } from "./scoring";
import { composeResultNarrative } from "./result-insights";

export const ASSESSMENT_FIXTURES: Record<string, readonly AnswerRecord[]> = {
  intjA5w6: [{ questionId: "f-ie-1", optionIndex: 0 }, { questionId: "f-ie-2", optionIndex: 0 }, { questionId: "f-sn-1", optionIndex: 0 }, { questionId: "f-sn-2", optionIndex: 3 }, { questionId: "f-tf-1", optionIndex: 2 }, { questionId: "f-tf-2", optionIndex: 1 }, { questionId: "f-jp-1", optionIndex: 3 }, { questionId: "f-jp-2", optionIndex: 1 }, { questionId: "f-e-1", optionIndex: 2 }, { questionId: "f-e-2", optionIndex: 1 }, { questionId: "f-e-3", optionIndex: 1 }, { questionId: "f-e-4", optionIndex: 2 }, { questionId: "f-e-5", optionIndex: 2 }, { questionId: "f-e-6", optionIndex: 2 }, { questionId: "f-e-7", optionIndex: 0 }, { questionId: "f-e-8", optionIndex: 2 }, { questionId: "f-e-9", optionIndex: 0 }, { questionId: "f-e-10", optionIndex: 2 }, { questionId: "c-at", optionIndex: 3 }, { questionId: "c-at2", optionIndex: 0 }, { questionId: "c-ie", optionIndex: 0 }, { questionId: "c-core-7", optionIndex: 1 }, { questionId: "c-core-5", optionIndex: 0 }, { questionId: "c-wing-5", optionIndex: 0 }],
  enfpT7w8: [{ questionId: "f-ie-1", optionIndex: 1 }, { questionId: "f-ie-2", optionIndex: 2 }, { questionId: "f-sn-1", optionIndex: 2 }, { questionId: "f-sn-2", optionIndex: 3 }, { questionId: "f-tf-1", optionIndex: 1 }, { questionId: "f-tf-2", optionIndex: 3 }, { questionId: "f-jp-1", optionIndex: 1 }, { questionId: "f-jp-2", optionIndex: 2 }, { questionId: "f-e-1", optionIndex: 2 }, { questionId: "f-e-2", optionIndex: 1 }, { questionId: "f-e-3", optionIndex: 0 }, { questionId: "f-e-4", optionIndex: 1 }, { questionId: "f-e-5", optionIndex: 0 }, { questionId: "f-e-6", optionIndex: 2 }, { questionId: "f-e-7", optionIndex: 2 }, { questionId: "f-e-8", optionIndex: 0 }, { questionId: "f-e-9", optionIndex: 1 }, { questionId: "f-e-10", optionIndex: 2 }, { questionId: "c-at", optionIndex: 0 }, { questionId: "c-at2", optionIndex: 2 }, { questionId: "c-sn", optionIndex: 1 }, { questionId: "c-core-2", optionIndex: 2 }, { questionId: "c-core-7", optionIndex: 0 }, { questionId: "c-wing-7", optionIndex: 0 }],
  clearCore4w5: [{ questionId: "f-ie-1", optionIndex: 0 }, { questionId: "f-ie-2", optionIndex: 3 }, { questionId: "f-sn-1", optionIndex: 0 }, { questionId: "f-sn-2", optionIndex: 0 }, { questionId: "f-tf-1", optionIndex: 0 }, { questionId: "f-tf-2", optionIndex: 0 }, { questionId: "f-jp-1", optionIndex: 0 }, { questionId: "f-jp-2", optionIndex: 0 }, { questionId: "f-e-1", optionIndex: 0 }, { questionId: "f-e-2", optionIndex: 3 }, { questionId: "f-e-3", optionIndex: 3 }, { questionId: "f-e-4", optionIndex: 1 }, { questionId: "f-e-5", optionIndex: 1 }, { questionId: "f-e-6", optionIndex: 0 }, { questionId: "f-e-7", optionIndex: 0 }, { questionId: "f-e-8", optionIndex: 3 }, { questionId: "f-e-9", optionIndex: 3 }, { questionId: "f-e-10", optionIndex: 0 }, { questionId: "c-at", optionIndex: 1 }, { questionId: "c-at2", optionIndex: 0 }, { questionId: "c-jp", optionIndex: 3 }, { questionId: "c-core-4", optionIndex: 3 }, { questionId: "c-wing-4", optionIndex: 1 }, { questionId: "c-sn", optionIndex: 1 }],
  ambiguousWing: [{ questionId: "f-ie-1", optionIndex: 1 }, { questionId: "f-ie-2", optionIndex: 0 }, { questionId: "f-sn-1", optionIndex: 1 }, { questionId: "f-sn-2", optionIndex: 0 }, { questionId: "f-tf-1", optionIndex: 2 }, { questionId: "f-tf-2", optionIndex: 1 }, { questionId: "f-jp-1", optionIndex: 1 }, { questionId: "f-jp-2", optionIndex: 0 }, { questionId: "f-e-1", optionIndex: 3 }, { questionId: "f-e-2", optionIndex: 3 }, { questionId: "f-e-3", optionIndex: 0 }, { questionId: "f-e-4", optionIndex: 0 }, { questionId: "f-e-5", optionIndex: 1 }, { questionId: "f-e-6", optionIndex: 1 }, { questionId: "f-e-7", optionIndex: 0 }, { questionId: "f-e-8", optionIndex: 0 }, { questionId: "f-e-9", optionIndex: 1 }, { questionId: "f-e-10", optionIndex: 1 }, { questionId: "c-at", optionIndex: 1 }, { questionId: "c-at2", optionIndex: 1 }, { questionId: "c-ie", optionIndex: 3 }, { questionId: "c-core-4", optionIndex: 2 }, { questionId: "c-core-5", optionIndex: 0 }, { questionId: "c-wing-5", optionIndex: 1 }],
  ambiguousCore: [],
};

export const FIXTURE_EXPECTATIONS = {
  intjA5w6: { mbti: "INTJ-A", core: 5, wing: 6 },
  enfpT7w8: { mbti: "ENFP-T", core: 7, wing: 8 },
  clearCore4w5: { mbti: null, mbtiConfidence: "ambiguous", core: 4, enneagramConfidence: "clear", wing: 5, wingStatus: "valid" },
  ambiguousWing: { core: 5, wing: null, wingStatus: "ambiguous" },
  ambiguousCore: { core: null, wing: null, wingStatus: "unavailable" },
} as const;

/** Lightweight deterministic checks available to local QA without a test dependency. */
export const RESULT_INSIGHT_CHECKS = Object.fromEntries(
  Object.entries(ASSESSMENT_FIXTURES).map(([name, answers]) => {
    const result = scoreAssessment(answers);
    const narrative = composeResultNarrative(result);
    return [name, {
      type: result.mbti.type,
      core: result.enneagram.core,
      wing: result.wing,
      wingStatus: result.wingStatus,
      hasWingDetail: narrative.wing !== null,
      narrative: narrative.narrative,
    }];
  }),
);
